### ISSUE TITLE
Add Juice hours huge lack of juice

### ISSUE THREAD

**Issue by Xgone-DEV** [Ermelber/ErmiiBot#3]
Noticed the lack of Juice hours, it is very important to have vitamin C hours. Without such hours, it is impossible to get our proper dose of vitamins on our daily life. 🍹🍹🍹🧃🧃🧃🍹🧃🍊🍊🍊🍊![igt4dsrxl9l91.jpg](https://github.com/user-attachments/assets/6cc5115e-f3ce-4529-a130-5738852e1b27)

**Comment by Ermelber** [comment]
My fellow juice drinker, you may suggest the time (and timezone) when this reminder shall be triggered and the images and messages. 

Thank you.

**Comment by Xgone-DEV** [comment]
Of course fellow juice brother:

It shall be at 6:00pm / 18:00 at the Atlantic Standard Timezone. As for the images i shall provide here now: 

![oiy4s50scur91.jpg](https://github.com/user-attachments/assets/58c6fead-0877-42f1-9dd6-62a4964f8666)

![sddefault.jpg](https://github.com/user-attachments/assets/71363f39-5ff0-47ad-9016-53565505a035)

![tumblr_m5wcehxetl1r6i84qo1_500.gif](https://github.com/user-attachments/assets/29dd51a7-637d-4f37-9937-2244cd74107f)

![__cirno_touhou_drawn_by_kame_kamepan44231__sample-ffdc772d43d16afb629803b436f9ced2.jpg](https://github.com/user-attachments/assets/3d30c8b9-67e6-4bf4-be3d-a061966c91ed)

![RDT_20240712_095152471806732636837558.jpg](https://github.com/user-attachments/assets/24e9b69f-9553-441a-8887-cfe3521e81b0)
